### ISSUE TITLE
How can to use? 

### ISSUE THREAD

**Issue by LucasAlgerDay** [Minori100/Amino.fix#1]
I don't know how can to use that, in samino put "import samino" but when put in this case "import amino" give me a error because "I don't have amino" (amino fix it is installed)

**Comment by Minori100** [comment]
Because you don't need to import amino. You need to umport aminofix. 

Example:

```
import asyncio
import aminofix

async def main():
    client = aminofix.Client()
    client.web_login(email='email',password='password')
    sub_client = aminofix.SubClient(comId='comId', profile=client.profile)
if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

Discord link - https://discord.gg/Bf3dpBRJHj

I'm sorry for not answering you for a long time ;3
